name: Pull Request Closed
concurrency:
  group: pr_${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  - name: Delete Cloudflare Preview Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: go-fjords/cloudflare-delete-deployments-action@main
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          project: portfolio
          account: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          branch: ${{ github.head_ref }}
